### PR TITLE
make better debug warnings for negative state variables, fix undocumented code objects, fix previous PR problems

### PR DESCRIPTION
**Pull request by Apeirogons**
This PR should help to debug whether or not the negative state variable warnings are important or not. If utils::capture.output can be loaded, the warning messages will show which lines have negative state variables. I think that these are genuine issues rather than problems with the warning system (see issue).

Also addresses some of the problems listed in the previous PR comments, including documentation and warning for non-capitalized state variables.
The new ONcalib.rda and ONcalib2brks.rda should now correctly give the same predictions as the old calibrations, something that I didn't think to check previously. I fixed the tests for this, but the test only works if anydate is installed (otherwise, it is skipped).

### CODE REVIEW

**Comment by bbolker** [comment]
GitHub is warning that this is closed with unmerged commits. Is that OK?

**Comment by Apeirogons** [comment]
Yeah, I realized that using require() in a package is a bad idea. I'm going to remove that and reopen with everything else.

**Comment by bbolker** [comment]
you know about `requireNamespace()`, right? (Accepted alternative to `require()` if you're just trying to figure out whether a package is available so you can use it conditionally)

**Comment by Apeirogons** [comment]
I did not at the time, but the function I was using is actually part of the base R utils.

**Pull request merged**
