### PR TITLE
Styling and Linting (Issue #21)

### PR DESCRIPTION
**Pull request by Apeirogons**
This PR used styler to enforce the automatically supported tidyverse style guide recommendations, with these notable additions:
- Each comment starts with `##`.
- Tabs = 4 spaces.
- Fixed an issue where `%>%` operators on a new line would sometimes be mis-indented. 

Additionally, it implements a linting procedure. Lints are saved into a folder for further examination. Default lintr settings are used except:
- The maximum line length is set to 120 characters (80 seemed aggressive)
- A very forgiving snake_case rule is used, allowing capital letters to appear anywhere. Additionally, symbols like beta0 are acceptable. This is meant to target only variables named with dotted.case or camelCase.
- The commented code linter is turned off.

There is now a makerule for styling/linting: make style.

### CODE REVIEW

**Comment by dushoff** [comment]
I think 80 is already pretty long. Not sure what the advantage of 120 is.

**Comment by Apeirogons** [comment]
Most of the instances of violating 80-character limits are just long comments or Roxygen documentation that seems fine being on one line. Even for code, 80 is pretty aggressive; 
```  object_name_linter = object_name_linter(styles = c("macpan_symbols", "macpan_snake", "snake_case"))```
is 101, and I wouldn't consider that to be an egregiously long line.

**Comment by bbolker** [comment]
This seems like a good idea (it will induce changes all over the place when initially implemented). I will merge it soon.

**Comment by Apeirogons** [comment]
Accidentally deleted branch, sorry.

**Comment by bbolker** [comment]
@Apeirogons , can you add some short instructions to the README file (later to be moved somewhere better like DEVELOPERS.md) to tell people how to quickly run `styler` on their code? (I'm not necessarily averse to doing this as an automatic GH action on push, but I'd like to start manually/I'd like to have this documented. In particular, @papsti will want to run the styler on her code before trying to merge in either direction, to avoid 9 million little tiny merge conflicts due to whitespace changes ...)

**Pull request merged**
