### PR TITLE
Create docs folder using pkgdown, add new suggests

### PR DESCRIPTION
**Pull request by Apeirogons**
Additionally, re-added anytime to suggests (it's in a test).
Auto-converted getting_started.Rnw to Rmd using https://rdrr.io/cran/mdsr/man/Rnw2Rmd.html (pkgdown requires all vignettes to be R markdown files). Turned off warnings for getting_started.Rmd.

### CODE REVIEW

**Comment by Apeirogons** [comment]
Actually, making new pull requests every time we make a change is probably not sustainable. Would it make sense to make a GitHub Action that runs pkgdown instead?

**Comment by bbolker** [comment]
@davidearn  might a little bit unhappy about having to work in Rmarkdown rather than Rnw but I guess he can get used to it ...

Can you clarify your last comment ("making new pull requests to update docs ...") ?

**Comment by Apeirogons** [comment]
We will need to run pkgdown::build_site() every time we want to update the documentation page created by pkgdown. I'm just thinking about the best way to maintain documentation page going forward; should we ask people to run pkgdown::build_site() upon making changes? Or, should we make a GitHub Action to automatically generate pkgdown documentation? 

Also, as Steve pointed out, we will need to convert the docs folder to a GitHub Pages site. To do this, @bbolker needs to change the repo's GitHub Pages location to the newly generated docs folder.

**Comment by bbolker** [comment]
Didn't see the last comment, but it's done now.

How about a "[build site]" (or some such) tag in a commit message that triggers the pkgdown rebuild?

Before we merge this we should re-rmarkdownify with an updated version of the getting started vignette (I had to change it a little bit) **and** give the markdownified version a visual check to make sure nothing got broken. I'm a little bit worried that there may have been TeX stuff in there (macro definitions etc.) that either would have gotten mangled on translation or simply wouldn't do anything in markdown?

**Comment by bbolker** [comment]
Yeah, the markdown version of `getting_started.Rnw` is pretty mangled. Can we make the `.Rmd` version a stub for now and add an issue to go through and translate/fix up manually?

**Pull request merged**
